#!/usr/bin/env ruby

require 'certified'

site 'http://community.opscode.com/api/v1'

cookbook 'java', '~> 1.39.0'
cookbook 'maven', '~> 2.1.0'
cookbook 'dojo-cookbook', :path => 'my_cookbooks/dojo-cookbook'
