# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "nrel/CentOS-6.7-x86_64"

  # rabbitmq admin
  config.vm.network :forwarded_port, guest: 15672, host: 15673
  # mongodb
  config.vm.network :forwarded_port, guest: 27017, host: 27018

  # config.vm.synced_folder "./share", "/vagrant_data"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 3
	  v.name = "dojo-chef"
  end

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "cookbooks"

    chef.add_recipe "java"
    chef.add_recipe "dojo-cookbook"

  end

end
